Universe = vanilla

RequestCpus = 8
Request_GPUs = 4
RequestMemory = 8Gb
+RequestWalltime = 259000

Requirements = (CUDACapability >= 3.5)&&(CUDAGlobalMemoryMb >= 8000.0)

Initialdir = /users/visics/gkouros/projects/nerf-repos/NeRD-Neural-Reflectance-Decomposition/condor
Executable = /users/visics/gkouros/projects/nerf-repos/NeRD-Neural-Reflectance-Decomposition/condor/run_nerf_job.sh
Arguments = tesla $(Cluster)

NiceUser = true

Log    =  ../logs/tesla/exp.$(Cluster).log
Output =  ../logs/tesla/exp.$(Cluster).out
Error  =  ../logs/tesla/exp.$(Cluster).err

Notification = Complete
Queue 1
